/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentParamsPicker: typeof import('./src/components/AgentParamsPicker.vue')['default']
    EditSettings: typeof import('./src/components/EditSettings.vue')['default']
    FormatedToolCallInProgress: typeof import('./src/components/FormatedToolCallInProgress.vue')['default']
    'IEosIcons:bubbleLoading': typeof import('~icons/eos-icons/bubble-loading')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    InferenceParamsForm: typeof import('./src/components/InferenceParamsForm.vue')['default']
    ManageBackends: typeof import('./src/components/ManageBackends.vue')['default']
    NavbarTask: typeof import('./src/components/navbars/NavbarTask.vue')['default']
    PromptNavbarLeft: typeof import('./src/components/navbars/PromptNavbarLeft.vue')['default']
    PromptProcessingProgress: typeof import('./src/components/PromptProcessingProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SamplingPresets: typeof import('./src/components/SamplingPresets.vue')['default']
    SidebarAgents: typeof import('./src/components/sidebars/SidebarAgents.vue')['default']
    SidebarInferParams: typeof import('./src/components/sidebars/SidebarInferParams.vue')['default']
    SidebarsDispatch: typeof import('./src/components/sidebars/SidebarsDispatch.vue')['default']
    SidebarTasks: typeof import('./src/components/sidebars/SidebarTasks.vue')['default']
    SidebarWorkflows: typeof import('./src/components/sidebars/SidebarWorkflows.vue')['default']
    SwToast: typeof import('./src/components/vibe/toast/SwToast.vue')['default']
    SwToastItem: typeof import('./src/components/vibe/toast/SwToastItem.vue')['default']
    TaskTools: typeof import('./src/components/TaskTools.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    ThinkingContent: typeof import('./src/components/ThinkingContent.vue')['default']
    ThinkingNode: typeof import('./src/components/ThinkingNode.vue')['default']
    ToolCallNode: typeof import('./src/components/ToolCallNode.vue')['default']
    ViewAgent: typeof import('./src/components/ViewAgent.vue')['default']
    ViewConf: typeof import('./src/components/ViewConf.vue')['default']
    WorkspacePicker: typeof import('./src/components/WorkspacePicker.vue')['default']
  }
}
